### ISSUE TITLE
Brining the xAxis lower down

### ISSUE THREAD

**Issue by ni14forgit** [chartiful/react-native-charts#4]
Hi this package is amazing thank you!

The graph doesn't end up taking as much space as it can (I have `startAtZero: true`) because the xAxis starts way above the yAxis. Is there any way to shift the xAxis down (along with the graph itself?)

Thanks, 
Nishant

**Comment by seanwatters** [comment]
Thanks for reaching out! Sorry for the delay—I'll look into this this evening and get back to you.

**Comment by seanwatters** [comment]
@ni14forgit can you send a screen shot of what you're talking about?

**Comment by ni14forgit** [comment]
<img width="300" alt="Screen Shot 2020-08-10 at 6 13 12 PM" src="https://user-images.githubusercontent.com/9367375/89836612-2a70b300-db35-11ea-8428-54129209cb5f.png">
This occurs when I set `hasXAxisLabels `and `hasYAxisLables` to `true`. 
It would be great if the 71 could be move lower, closer to the 0, rather than starting around the middle position, that way the graph can take up more height.

**Comment by seanwatters** [comment]
Ah, I see. So if you modify the `yAxisLabelStyle: { height: ... }` prop, you should be able to make that adjustment.

```jsx
<LineGraph 
  baseConfig={{
    ...,
    yAxisLabelStyle: {
      height: 30 // (defaults to 50)
    }
  }}
/>
```

^^^ should help with your problem.

**Comment by ni14forgit** [comment]
Ah, thank you Sean!
